---
:verbose: false
:concurrency: 6
:logfile: ./log/sidekiq.json.log
:queues:
  - downstream_high
  - dependency_resolution
  - downstream_low
  - downstream_deferred
  - experiments
  - default
  - import
